# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
# seed-isort-config is no longer needed as of isort>=5
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.5.4
  hooks:
  - id: isort
    args: [-m, '3', -tc]
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [-l 88]
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
  - id: docformatter
    args: [--in-place, -r, --blank, --pre-summary-newline]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    args: [--max-complexity, '12', --ignore, 'E203,E501,W503']
